Tutorial/oop
ICESAT-2HackWeek/website2022 pull request #83
Opened 2022-03-18 16:18 UTC by RomiP

add OOP tutorial files for participants and include in heading in _toc.yml

2022-03-18 17:50 UTC, scottyhq commented on book/_toc.yml
> +        - file: tutorials/DataIntegration/dataintegration-2
```suggestion
```

2022-03-18 17:51 UTC, scottyhq requested changes
Thanks @RomiP ! see comments and suggested changes

2022-03-18 22:36 UTC, scottyhq commented on book/_toc.yml
> +            - file: tutorials/ObjectOriented/alien
Looks like these are just bare notebooks without explanatory text, is the idea is to have them easily accessible for participants, rather than rendered on the website? If so, we can remove them from table of contents.

```suggestion
```

2022-03-19 18:21 UTC, RomiP commented on book/_toc.yml
> +            - file: tutorials/ObjectOriented/alien
Yes, the idea is to just have them easily accessible to participants. I'm ok with removing it from the table of contents.

2022-03-20 17:35 UTC, scottyhq approved these changes

2022-03-20 17:36 UTC, merged